spring.application.name=patient-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.h2.console.enabled=${SPRING_H2_CONSOLE_ENABLED:true}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:update}
spring.jpa.defer-datasource-initialization=true

server.port=${SERVER_PORT:4000}

logging.level.root=info
